apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    name: postgres-pod
    app: db-app
spec:
  containers:
    - name: db-container
      image: postgres:9.4
      ports:
        - containerPort: 5432