apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    name: postgres-pod
    app: voting-app
spec:
  containers:
    - name: postgres
      image: postgres:9.4
      env:
        - name: POSTGRES_PASSWORD
          value: mysecretpassword
      ports:
        - containerPort: 5432
