apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    app: db
spec:
  type: ClusterIP
  selector:
    name: postgres-pod
    app: db-app
  ports:
    - targetPort: 5432
      port: 5432
