apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: redis
spec:
  type: ClusterIP
  selector:
    name: redis-pod
    app: redis-app
  ports:
    - targetPort: 6379
      port: 6379