apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: redis-pod
    app: redis-app
spec:
  containers:
    - name: redis-container
      image: redis
      ports:
        - containerPort: 6379