apiVersion: v1
kind: Pod
metadata:
  name: result-pod
  labels:
    name: result-pod
    app: result-app
spec:
  containers:
    - name: result-container
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80