apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: frontend
spec:
  type: NodePort
  selector:
    name: result-pod
    app: result-app
  ports:
    - targetPort: 80
      port: 30081
      nodePort: 30081