apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: frontend
spec:
  type: NodePort
  selector:
    name: voting-pod
    app: voting-app
  ports:
    - targetPort: 80
      port: 30080
      nodePort: 30080