apiVersion: v1
kind: Pod
metadata:
  name: worker
  labels:
    name: worker-pod
    app: worker-app
spec:
  containers:
    - name: worker-container
      image: dockersamples/examplevotingapp_worker
      ports:
        - containerPort: 80